Pivot Tables

In [1]:
import numpy as np 
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

In [4]:
df = pd.DataFrame(data)

In [5]:
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    379     95   John
1  2023-01-02       B   West    958     85   Mary
2  2023-01-03       C  North    810     81    Bob
3  2023-01-04       D  South    285     85  Alice
4  2023-01-05       A   East    129     56   John
5  2023-01-06       B   West    336     25   Mary
6  2023-01-07       C  North    516     13    Bob
7  2023-01-08       D  South    215     42  Alice
8  2023-01-09       A   East    365     49   John
9  2023-01-10       B   West    172     97   Mary
10 2023-01-11       C  North    560     99    Bob
11 2023-01-12       D  South    585     20  Alice
12 2023-01-13       A   East    684     43   John
13 2023-01-14       B   West    224     61   Mary
14 2023-01-15       C  North    648     75    Bob
15 2023-01-16       D  South    318     81  Alice
16 2023-01-17       A   East    618     83   John
17 2023-01-18       B   West    618     99   Mary
18 2023-01-19       C  North    607     43    Bob
19 2023-01-20       D  South    278     84  Alice

In [7]:
pd.pivot_table(df, values= 'Sales', index= 'Region', columns= 'Product' )

Product      A      B      C      D
Region
East     435.0    NaN    NaN    NaN
North      NaN    NaN  628.2    NaN
South      NaN    NaN    NaN  336.2
West       NaN  461.6    NaN    NaN

In [10]:
pd.pivot_table(df, values= ['Sales','Units'], index= 'Region', columns= 'Product' )

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     435.0    NaN    NaN    NaN  65.2   NaN   NaN   NaN
North      NaN    NaN  628.2    NaN   NaN   NaN  62.2   NaN
South      NaN    NaN    NaN  336.2   NaN   NaN   NaN  62.4
West       NaN  461.6    NaN    NaN   NaN  73.4   NaN   NaN

Cross Tabs

In [11]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0